/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ShiftReg_5.h"
#include "ShiftReg_6.h"
#include "ShiftReg_7.h"
#include "ShiftReg_8.h"
#include "Count7_1.h"
#include "Control_Reg_1.h"
#include "Channel1_R_aliases.h"
#include "Channel1_R.h"
#include "EN_Channel1.h"
#include "Sel_Gen_Channel1.h"
#include "SWReg_Channel1.h"
#include "ADC_Channel1.h"
#include "PGA_Channel1.h"
#include "Vout_R1_aliases.h"
#include "Vout_R1.h"
#include "Opamp_Channel1.h"
#include "Cap1_4_aliases.h"
#include "Cap1_4.h"
#include "Cap1_3_aliases.h"
#include "Cap1_3.h"
#include "Cap1_2_aliases.h"
#include "Cap1_2.h"
#include "Cap1_1_aliases.h"
#include "Cap1_1.h"
#include "Channel_1_aliases.h"
#include "Channel_1.h"
#include "Clock_1.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "Pin_3_aliases.h"
#include "Pin_3.h"
#include "Opamp_Channel1_1.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "USBUART_1.h"
#include "USBUART_1_audio.h"
#include "USBUART_1_cdc.h"
#include "USBUART_1_hid.h"
#include "USBUART_1_midi.h"
#include "USBUART_1_pvt.h"
#include "USBUART_1_cydmac.h"
#include "USBUART_1_msc.h"
#include "USB_isr.h"
#include "ADC_Channel1_IRQ.h"
#include "ADC_Channel1_theACLK.h"
#include "USBUART_1_Dm_aliases.h"
#include "USBUART_1_Dm.h"
#include "USBUART_1_Dp_aliases.h"
#include "USBUART_1_Dp.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

